### PR TITLE
feat: release v1.0.3

### PR DESCRIPTION
**Pull request by raditotev**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes [44660](https://github.com/freeCodeCamp/freeCodeCamp/issues/44660)

### CODE REVIEW

**Comment by raditotev** [comment]
@gikf I think I followed the instructions to the letter. If I've missed anything let me know.

Note: I couldn't manage to get to the last exercise when testing the changes but I did the first three/four with the changes on my branch and they've worked as expected.

**Comment by raditotev** [comment]
I forgot to include the SQL query changes in this PR. To keep git commit history I've applied the changes using  interactive rebase. That is the reason for the last two force pushes.

**Comment by gikf** [comment]
@raditotev thanks for tacking this. Changes on version branch are done in correct way. I've checked changed query on the data, it should do the work.

I've found two details:
- First course name is missing 's', name in database is `Computer Networks`. This is both on the version branch and main branch.
- On version branch, in commit `2460.1`, file `.freeCodeCamp/reset_files/student_info.sh` has still old query added.

**Comment by raditotev** [comment]
@gikf nice catch, thanks. While making the necessary changes I have realised I placed the correct SQL query in the wrong hint - "Try entering this...". I have changed that as well and now the query is where it should be - in the last hint.

**Comment by gikf** [comment]
Actually shouldn't they both have it changed?

`SELECT COUNT(course), COURSE FROM students FULL JOIN majors USING(major_id) FULL JOIN majors_courses USING(major_id) FULL JOIN courses USING(course_id) GROUP BY course;` displays numbers corresponding to the for the previous answer:
```
+-------+--------------------------------+
| count |             course             |
+-------+--------------------------------+
|     0 |                                |
|     7 | Object-Oriented Programming    |
|    16 | Data Structures and Algorithms |
|     7 | Algorithms                     |
|     6 | Artificial Intelligence        |
|     1 | UNIX                           |
|     6 | Game Architecture              |
|     5 | Python                         |
|     6 | SQL                            |
|     1 | Server Administration          |
|     1 | Network Security               |
|     4 | Machine Learning               |
|    10 | Calculus                       |
|    12 | Web Applications               |
|     3 | Computer Networks              |
|     6 | Web Programming                |
|     3 | Computer Systems               |
|     6 | Database Systems               |
+-------+--------------------------------+
```
Changing `FULL JOIN`s to `INNER JOIN`s reveals right values for the wanted answers.

I've pushed [`v1.0.3`](https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-2/tree/v1.0.3) branch to this repository. You can now also update `uri` to point to `freeCodeCamp` repository.

**Comment by raditotev** [comment]
I assumed this is broad direction to the right answer. If you feel this hint should be changed as well, I'll change it, so that is closer to the right answer.

**Comment by raditotev** [comment]
Actually looking at what the query is returning I think you're right. This should change as well.

**Comment by gikf** [comment]
Yeah, due to _not desired_ values received I feel it might be slightly misleading. With just changing the kind of `JOIN`s used, there's still couple additions necessary to get the full answer, but the numbers would indicate this is the right path.

**Comment by raditotev** [comment]
@gikf done.

**Review by gikf — APPROVED** [review]
Great!

Looks good to me :+1:

**Comment by moT01** [comment]
Thanks for the work on this @raditotev 🎉 and getting this in @gikf 🎉 

I gave this a test and it LGTM

just a heads up, these are live now so we want be extra careful when moving to new versions 👍

**Pull request merged**
