### PR TITLE
fix: improve instructions to step 2250

### PR DESCRIPTION
**Pull request by akalezic**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/44659

https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-2/pull/15 
I think I followed all of the instructions provided in the link but let me know if I'm missing anything or did anything wrong! @gikf

### CODE REVIEW

**Comment by akalezic** [comment]
Hi! I just removed all of the `\r`'s, removed the version from the changelog, and added the clearer instruction you provided. Thanks for the suggestions and clarification!

**Review by gikf — CHANGES_REQUESTED** [review]
Wording in `tutorial.json` wasn't updated after the latest change. Could you correct that?

**Comment by akalezic** [comment]
@gikf done! sorry I missed that

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by moT01 — APPROVED** [review]
LGTM @akalezic 🎉 Thanks for working on this 🎉

**Pull request merged**
