### PR TITLE
fix: improved statement by adding "an"

### PR DESCRIPTION
**Pull request by srkds**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes    #44772 [issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/44772)

before:
In your student info script, add echo statement at the bottom like the other to print the results of the suggested query.

after:
In your student info script, add an echo statement at the bottom like the other to print the results of the suggested query.

### CODE REVIEW

**Review by import-brain — APPROVED** [review]

**Comment by import-brain** [comment]
Please mark as ready for review :)

**Review by gikf — CHANGES_REQUESTED** [review]
This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Happy contributing.

---

Note for future - it is recommended to make changes on a separate branch of the fork, than the `main` branch.

**Comment by srkds** [comment]
Thanks for your comment.

so according to your suggestion first I make a separate branch from the main of the fork and then make PR?

**Comment by gikf** [comment]
Yes, that way, the `main` branch of the fork can be kept clean and in sync of the `main` branch in the original repository. This will allow for it to be used, without any issues, as a base for future branches and new PRs.

**Comment by srkds** [comment]
please check #6

**Comment by gikf** [comment]
> please check #6

It uses different branch than `main`, yes. However it doesn't respond to the first part of my first comment - change in tutorial using CodeRoad VS extension requires following specific workflow. Changing `TUTORIAL.md` is just a part of that workflow.

**Comment by gikf** [comment]
Hey @srkds

Thank you for opening this pull request.

As there was different PR - #7 - following required workflow merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://chat.freecodecamp.org/channel/contributors).

**Comment by srkds** [comment]
Thank you for your suggestion and support 👍

**Pull request closed without merging**
